name: Unit testing
on:
  push:
    branches:
      - v2
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    env:
      SRC: ${{ github.workspace }}/v2
      DEV: ${{ github.workspace }}/dev
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: 'v2'
          ref: 'v2'
      - name: Check out test code
        uses: actions/checkout@v2
        with:
          path: 'dev'
          ref: 'dev'
      - name: Do testing
        run: |
          ln -s "$SRC" "${DEV}/src"
          cd "${DEV}/test"
          make start
      - name: Coveralls
        env:
          GO111MODULE: off
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          REPO_BASE: /home/runner/go/src/github.com
        run: |
          REPO="${REPO_BASE}/${GITHUB_REPOSITORY}"
          mkdir -p "${REPO_BASE}/${GITHUB_ACTOR}"
          ln -s "$SRC" "$REPO"
          cd "$REPO"
          go get github.com/mattn/goveralls
          goveralls "-coverprofile=${DEV}/test/coverage.out"
